### CREATE LABECLASS
POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Lamarr",
    "module": "0"
}

### CREATE STUDENT
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Nei",
    "email": "nei@email.com",
    "birthDate": "05/04/1995",
    "labeClass": "Lamarr",
    "hobbies": ["correr", "malhar", "estudar"]
}


### GET CLASSES
GET http://localhost:3003/classes

### GET STUDENT
GET http://localhost:3003/student

### GET TEACHERS
GET http://localhost:3003/teachers